version: '3'

services:
  wtddev:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./:/home/devbox/workspace/:rw
    command: ["bash", "-c", "npm install && npm run build && npm run dev"]
    working_dir: /home/devbox/workspace
    container_name: wtddev
