name: Build

on: push

jobs:
  build:
    name: wtd
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Build
      shell: bash
      run: |
        npm ci
        npm run build
    - name: Test
      shell: bash
      run: |
        npm run test
    - name: Build Production
      shell: bash
      run: |
        npm --prefix packages/examples run build:production
    - name: Lint
      shell: bash
      run: |
        npm run lint
