name: Build

on:
  push:
      branches-ignore:
        - "ghp"
      tags-ignore:
        - "v*.*.*"

jobs:
  build:
    name: wtd
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Volta
      uses: volta-cli/action@v4

    - name: Install
      run: |
        npm ci

    - name: Lint
      run: |
        npm run lint

    - name: Build
      run: |
        npm run build

    - name: Test
      run: |
        npm run test

    # Always check if production build works
    - name: Build Production
      run: |
        npm run build:production
